name: Deploy Command Handler Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Build the project
      run: dotnet build azure-functions/command-handler/CommandHandler.csproj --configuration Release

    - name: Publish the project
      run: dotnet publish azure-functions/command-handler/CommandHandler.csproj --configuration Release --output ./output

    - name: Deploy to Azure Function
      uses: Azure/functions-action@v1
      with:
        app-name: 'commandHandlerFunction'
        package: './output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_COMMAND_HANDLER }}
